doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'VehicleFleet\Infra\Doctrine\ORM\Migrations': '%kernel.project_dir%/src/Infra/Doctrine/ORM/Migrations'
    enable_profiler: '%kernel.debug%'
