version: "3.9"
services:
    vf-php:
        container_name: vf-php
        build:
            context: ./docker/php
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www
