#!/bin/bash -eu
set -o pipefail

ACTION="$1"

case $ACTION in

  create)
    docker-compose exec vf-php php bin/console vehicle-fleet:fleet:create $2
    ;;

  register-vehicle)
    docker-compose exec vf-php php bin/console vehicle-fleet:vehicle:register $2 $3
    ;;

  localize-vehicle)
    docker-compose exec vf-php php bin/console vehicle-fleet:vehicle:park $2 $3 $4 $5 ${6-}
    ;;

  *)
    echo "Je ne sais pas quoi faire avec '$ACTION'"
    ;;
esac
